### ISSUE TITLE
Some suggestion to cordidator plugin

### ISSUE THREAD

**Issue by TymekSL** [Mirroray41/Coordinator#1]
1. First of all discord support server (faster way to support)
2. 1.8 - 1.20 ? 
3. Hex colors in bossbar?
4. /cr on /cr off - turn on / off the visibility
5. nice to see the placeholder + option to disable the bossbar, I know it breaking all plugin idea but I would paste this placerholder into my tab because using the tab from bossbar + coordinator tab - both will be break and will be animate (I Think) coordinator bossbar/tab bossbar/coordinator / tab 
6. permission example coordinator.use (meaby customizable permission?) coordinator.admin to reload cmd 
7. reload command + console support 
8. Commands after # with the description what this doing / where can use this because now I don't know https://prnt.sc/xUeHYVTpZmkN 
ok,let's starting tests xD

**Comment by Mirroray41** [comment]
1. As im not that active and I am the sole developer of this plugin, I'm not sure if I want to provide a discord support server, but ill look into it later.
2. Ill look into a broader version support for 1.2.
3. Hex colors are planed for 1.2 too
4. as its possible in the player config gui, I dont see why there would be a explicit command needed.
5. I didnt understand this sugestion, please try to revrite it in better english because english isnt my first language too.
6. -7. Nice idea too add the use permision, but there is already a reload command(I just didnt mention it anywhere, upsie) with its own permision "cr.reload"
8. prefixes mentioned here apply to the bossbar parts displayed(if you want to have colors there)

**Comment by TymekSL** [comment]
5. Disable option

**Comment by TymekSL** [comment]
With placeholder same what will be display in the bossbar. So makr this with placeholder %coordinator% example, and i would use this on the tab bossbae instead of coordinator. If you still dont understand its not my problem learn english

**Comment by Mirroray41** [comment]
added your suggestions in 1.2
